version: '3.8'

services:
  # Development Next.js Application with hot reload
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: bsv-torrent-app-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongodb:27017/bsv-torrent
      MONGODB_DB: bsv-torrent

      # BSV Configuration (testnet for development)
      BSV_NETWORK: testnet
      BSV_MNEMONIC: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
      BSV_WALLET_PATH: "m/44'/236'/0'"

      # Development URLs
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      NEXT_PUBLIC_BSV_NETWORK: testnet

      # Enable development features
      NEXT_TELEMETRY_DISABLED: 1
      WATCHPACK_POLLING: true

    depends_on:
      - mongodb
      - redis
    networks:
      - bsv-torrent-network
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/node_modules
      - /app/.next
      - torrent-data:/app/data
      - uploads:/app/uploads

  # MongoDB Database (no auth for development)
  mongodb:
    image: mongo:7.0-jammy
    container_name: bsv-torrent-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: bsv-torrent
    volumes:
      - mongodb-data:/data/db
      - ./docker/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - bsv-torrent-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: bsv-torrent-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - bsv-torrent-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB Express (Web UI for MongoDB)
  mongo-express:
    image: mongo-express:latest
    container_name: bsv-torrent-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - bsv-torrent-network

  # Redis Commander (Web UI for Redis)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: bsv-torrent-redis-commander
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      REDIS_HOSTS: local:redis:6379
    depends_on:
      - redis
    networks:
      - bsv-torrent-network

networks:
  bsv-torrent-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
  redis-data:
    driver: local
  torrent-data:
    driver: local
  uploads:
    driver: local